package de.tbosch.aufzugseile.gui;

import de.tbosch.aufzugseile.gui.aufzug.AufzugschachtDoppelUmlenkrolle;
import de.tbosch.aufzugseile.gui.aufzug.AufzugschachtRolle;
import java.awt.Insets;
import java.text.DecimalFormat;
import java.text.ParseException;

import javax.swing.ImageIcon;

import de.tbosch.commons.Helper;
import de.tbosch.commons.gui.GUICommonsConstants;
import de.tbosch.seile.commons.elemente.Rolle;

/**
 * The Class RollenParameterPanel.
 * 
 * @author  bobo
 */
public class RollenParameterPanel extends javax.swing.JPanel {

	/** The roll. */
	private AufzugschachtRolle rolle;
	
	/** The main frame. */
	private MainFrame mainFrame;
	
	/** The df_nopoint. */
	private DecimalFormat df_point, df_nopoint;
    
    /**
     * Creates new form RollenParameterPanel.
     * 
     * @param rolle the roll
     * @param mainFrame the main frame
     */
    public RollenParameterPanel(AufzugschachtRolle rolle, MainFrame mainFrame) {
    	df_point = new DecimalFormat();
		df_point.setMaximumFractionDigits(2);
		df_point.setMinimumFractionDigits(0);
		df_point.setGroupingUsed(false);
		df_nopoint = new DecimalFormat();
		df_nopoint.setMaximumFractionDigits(0);
		df_nopoint.setGroupingUsed(false);
    	initComponents();
    	this.rolle = rolle;
		this.mainFrame = mainFrame;
		seiltriebwirkungsgradFormattedTextField.setText(df_point.format(rolle.getFs2()));
		schraegzugFormattedTextField.setText(df_point.format(rolle.getFn4()));
		durchmesserFormattedTextField.setText(df_nopoint.format(rolle.getDurchmesser()));
		seilrilleFormattedTextField.setText(df_point.format(rolle.getFn3()));
		if (rolle.isGegenbiegung()) {
			gegenbiegungCheckBox.setSelected(true);
		}
		else {
			gegenbiegungCheckBox.setSelected(false);
		}
		
		lockToggleButton.setSelectedIcon(new ImageIcon(Helper.getFileURL(GUICommonsConstants.LOCKED_ICON)));
		lockToggleButton.setIcon(new ImageIcon(Helper.getFileURL(GUICommonsConstants.UNLOCKED_ICON)));
		lockToggleButton.setMargin(new Insets(0,0,0,0));
		
		if (rolle.isGegenbiegungNotChangeable()) {
			lockToggleButton.setSelected(true);
			lockToggleButtonActionPerformed(null);
		}
		else {
			lockToggleButton.setSelected(false);
			lockToggleButtonActionPerformed(null);
		}
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        seiltriebwirkungsgradLabel = new javax.swing.JLabel();
        schraegzugLabel = new javax.swing.JLabel();
        seiltriebwirkungsgradFormattedTextField = new javax.swing.JFormattedTextField(df_point);
        schraegzugFormattedTextField = new javax.swing.JFormattedTextField(df_point);
        durchmesserEinheitLabel = new javax.swing.JLabel();
        durchmesserLabel = new javax.swing.JLabel();
        seilrilleLabel = new javax.swing.JLabel();
        gegenbiegungLabel = new javax.swing.JLabel();
        gegenbiegungCheckBox = new javax.swing.JCheckBox();
        durchmesserFormattedTextField = new javax.swing.JFormattedTextField(df_nopoint);
        seilrilleFormattedTextField = new javax.swing.JFormattedTextField(df_point);
        lockToggleButton = new javax.swing.JToggleButton();

        jScrollPane1.setBorder(null);

        seiltriebwirkungsgradLabel.setText("Seiltriebwirkungsgrad (fs2):");

        schraegzugLabel.setText("Schrägzug (fn4):");

        seiltriebwirkungsgradFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seiltriebwirkungsgradFormattedTextFieldKeyReleased(evt);
            }
        });

        schraegzugFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                schraegzugFormattedTextFieldKeyReleased(evt);
            }
        });

        durchmesserEinheitLabel.setText("mm");

        durchmesserLabel.setText("Durchmesser:");

        seilrilleLabel.setText("Seilrille (fn3):");

        gegenbiegungLabel.setText("Gegenbiegung vor der Rolle:");

        gegenbiegungCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        gegenbiegungCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gegenbiegungCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gegenbiegungCheckBoxActionPerformed(evt);
            }
        });

        durchmesserFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                durchmesserFormattedTextFieldKeyReleased(evt);
            }
        });

        seilrilleFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                seilrilleFormattedTextFieldKeyReleased(evt);
            }
        });

        lockToggleButton.setToolTipText("lock");
        lockToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockToggleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(seiltriebwirkungsgradLabel)
                    .addComponent(schraegzugLabel)
                    .addComponent(durchmesserLabel)
                    .addComponent(seilrilleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(seilrilleFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(durchmesserFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(seiltriebwirkungsgradFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(schraegzugFormattedTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(durchmesserEinheitLabel))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gegenbiegungLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gegenbiegungCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lockToggleButton))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(durchmesserLabel)
                    .addComponent(durchmesserFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durchmesserEinheitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seiltriebwirkungsgradLabel)
                    .addComponent(seiltriebwirkungsgradFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seilrilleFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seilrilleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(schraegzugLabel)
                    .addComponent(schraegzugFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(gegenbiegungLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lockToggleButton)
                    .addComponent(gegenbiegungCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gegenbiegung check box action performed.
     * 
     * @param evt the evt
     */
    private void gegenbiegungCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gegenbiegungCheckBoxActionPerformed
    	boolean gegen = gegenbiegungCheckBox.isSelected();
		rolle.setGegenbiegung(gegen);
		mainFrame.parameterChanged();
    }//GEN-LAST:event_gegenbiegungCheckBoxActionPerformed

    /**
     * Seilrille formatted text field key released.
     * 
     * @param evt the evt
     */
    private void seilrilleFormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seilrilleFormattedTextFieldKeyReleased
    	try {
			double doub = (df_point.parse(seilrilleFormattedTextField.getText())).doubleValue();
			rolle.setSeilrille(doub);
			if (rolle.isPartOfDoppelUmlenkrolle()) {
				rolle.getBrother().setSeilrille(doub);
			}
			mainFrame.parameterChanged();
		}
		catch (ParseException e) {
			// auto-correction by FormattedTextField
		}
    }//GEN-LAST:event_seilrilleFormattedTextFieldKeyReleased

    /**
     * Schraegzug formatted text field key released.
     * 
     * @param evt the evt
     */
    private void schraegzugFormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_schraegzugFormattedTextFieldKeyReleased
    	try {
			double doub = (df_point.parse(schraegzugFormattedTextField.getText())).doubleValue();
			rolle.setSchraegzug(doub);
			if (rolle.isPartOfDoppelUmlenkrolle()) {
				rolle.getBrother().setSchraegzug(doub);
			}
			mainFrame.parameterChanged();
		}
		catch (ParseException e) {
			// auto-correction by FormattedTextField
		}
    }//GEN-LAST:event_schraegzugFormattedTextFieldKeyReleased

    /**
     * Seiltriebwirkungsgrad formatted text field key released.
     * 
     * @param evt the evt
     */
    private void seiltriebwirkungsgradFormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_seiltriebwirkungsgradFormattedTextFieldKeyReleased
    	try {
			double doub = (df_point.parse(seiltriebwirkungsgradFormattedTextField.getText())).doubleValue();
			rolle.setSeiltriebwirkungsgrad(doub);
			if (rolle.isPartOfDoppelUmlenkrolle()) {
				rolle.getBrother().setSeiltriebwirkungsgrad(doub);
			}
			mainFrame.parameterChanged();
		}
		catch (ParseException e) {
			// auto-correction by FormattedTextField
		}
    }//GEN-LAST:event_seiltriebwirkungsgradFormattedTextFieldKeyReleased

    /**
     * Durchmesser formatted text field key released.
     * 
     * @param evt the evt
     */
    private void durchmesserFormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_durchmesserFormattedTextFieldKeyReleased
    	try {
			int integer = (df_nopoint.parse(durchmesserFormattedTextField.getText()).intValue());
			rolle.setDurchmesser(integer);
			if (rolle.isPartOfDoppelUmlenkrolle()) {
				rolle.getBrother().setDurchmesser(integer);
				((AufzugschachtDoppelUmlenkrolle)rolle.getParentDoubleRoll()).refreshSize();
			}
			mainFrame.parameterChanged();
		}
		catch (ParseException e) {
			// auto-correction by FormattedTextField
		}
    }//GEN-LAST:event_durchmesserFormattedTextFieldKeyReleased

    private void lockToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockToggleButtonActionPerformed
    	if (lockToggleButton.isSelected()) {
    		rolle.setGegenbiegungNotChangeable(true);
    		gegenbiegungCheckBox.setEnabled(false);
    	}
    	else {
    		rolle.setGegenbiegungNotChangeable(false);
    		gegenbiegungCheckBox.setEnabled(true);
    	}
    }//GEN-LAST:event_lockToggleButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel durchmesserEinheitLabel;
    private javax.swing.JFormattedTextField durchmesserFormattedTextField;
    private javax.swing.JLabel durchmesserLabel;
    private javax.swing.JCheckBox gegenbiegungCheckBox;
    private javax.swing.JLabel gegenbiegungLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton lockToggleButton;
    private javax.swing.JFormattedTextField schraegzugFormattedTextField;
    private javax.swing.JLabel schraegzugLabel;
    private javax.swing.JFormattedTextField seilrilleFormattedTextField;
    private javax.swing.JLabel seilrilleLabel;
    private javax.swing.JFormattedTextField seiltriebwirkungsgradFormattedTextField;
    private javax.swing.JLabel seiltriebwirkungsgradLabel;
    // End of variables declaration//GEN-END:variables

	/**
     * Gets the rolle.
     * 
     * @return the rolle
     */
    public Rolle getRolle() {
		return rolle;
	}

	/**
	 * Gets the durchmesser formatted text field.
	 * 
	 * @return the durchmesser formatted text field
	 */
	public javax.swing.JFormattedTextField getDurchmesserFormattedTextField() {
		return durchmesserFormattedTextField;
	}

	/**
	 * Gets the gegenbiegung check box.
	 * 
	 * @return the gegenbiegung check box
	 */
	public javax.swing.JCheckBox getGegenbiegungCheckBox() {
		return gegenbiegungCheckBox;
	}

	/**
	 * Gets the schraegzug formatted text field.
	 * 
	 * @return the schraegzug formatted text field
	 */
	public javax.swing.JFormattedTextField getSchraegzugFormattedTextField() {
		return schraegzugFormattedTextField;
	}

	/**
	 * Gets the seilrille formatted text field.
	 * 
	 * @return the seilrille formatted text field
	 */
	public javax.swing.JFormattedTextField getSeilrilleFormattedTextField() {
		return seilrilleFormattedTextField;
	}

	/**
	 * Gets the seiltriebwirkungsgrad formatted text field.
	 * 
	 * @return the seiltriebwirkungsgrad formatted text field
	 */
	public javax.swing.JFormattedTextField getSeiltriebwirkungsgradFormattedTextField() {
		return seiltriebwirkungsgradFormattedTextField;
	}

	/**
	 * Sets the roll.
	 * 
	 * @param rolle the roll
	 */
	public void setRolle(AufzugschachtRolle rolle) {
		this.rolle = rolle;
	}
    
}
