package de.tbosch.aufzugseile.gui;

import java.awt.Font;
import java.util.Vector;
import java.util.logging.Level;

import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import de.tbosch.commons.gui.DialogFrame;
import de.tbosch.commons.gui.ErrorFrame;
import de.tbosch.commons.Helper;
import de.tbosch.commons.SystemConstants;
import de.tbosch.commons.gui.GUIHelper;
import de.tbosch.aufzugseile.gui.utils.Constants;
import de.tbosch.commons.FileSetWritableException;
import de.tbosch.commons.gui.Reactor;
import java.awt.Component;
import java.util.logging.Logger;

/**
 *
 * @author  schulung
 */
public class SeilParameterFrame extends javax.swing.JFrame implements Reactor {
    
    /** The Logger */
    private static final Logger logger = Logger.getLogger(SeilParameterFrame.class.getName());

	/** The main frame. */
	private MainFrame mainFrame;
	
	/** The dialog frame. */
	private DialogFrame dialogFrame;
	
	/** The opened boolean. */
	private boolean opened = false;
    
    /** Creates new form SeilParameterFrame */
    public SeilParameterFrame(MainFrame mainFrame, TableModel tableModel) {
        initComponents();
        this.mainFrame = mainFrame;
        if (tableModel != null) parameterTable.setModel(tableModel);
        setParameterTableLook();
    	
		ImageIcon imageIcon = new ImageIcon(Helper.getFileURL(Constants.PROGRAM_ICON));
		setIconImage(imageIcon.getImage());
    }
    
    private void setParameterTableLook() {
    	int br = 60;
    	parameterTable.getTableHeader().setReorderingAllowed(false);
    	parameterTable.getTableHeader().setFont(new Font("Dialog", 0, 10));
    	parameterTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        parameterTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        parameterTable.getColumnModel().getColumn(0).setResizable(false);
        parameterTable.getColumnModel().getColumn(1).setPreferredWidth(180);
        parameterTable.getColumnModel().getColumn(2).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(3).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(4).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(5).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(6).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(7).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(8).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(9).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(10).setPreferredWidth(br);
        parameterTable.getColumnModel().getColumn(11).setPreferredWidth(br+10);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    @SuppressWarnings("serial")
	private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        parameterTable = new javax.swing.JTable();
        hinzuButton = new javax.swing.JButton();
        entfButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seiltypparameter");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Parameter der verschiedenen Seiltypen");

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        parameterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {new Boolean(true), "8x19S-FE sZ", new Double(-2.611), new Double(-2.927), new Double(1.887), new Double(8.567), new Double(-0.32), new Double(-2.894), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.35), new Double(1770.0)},
                {null, "8x19S-FE zZ", new Double(-2.388), new Double(-2.704), new Double(1.887), new Double(8.567), new Double(-0.32), new Double(-2.894), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.35), new Double(1770.0)},
                {null, "8x19S-SES sZ", new Double(-2.148), new Double(-2.534), new Double(1.588), new Double(8.056), new Double(-0.32), new Double(-2.577), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.42), new Double(1770.0)},
                {null, "8x19S-SES zZ", new Double(-2.088), new Double(-2.474), new Double(1.588), new Double(8.056), new Double(-0.32), new Double(-2.577), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.42), new Double(1770.0)},
                {new Boolean(true), "8x19F/W-FE sZ", new Double(-2.476), new Double(-2.792), new Double(1.887), new Double(8.567), new Double(-0.32), new Double(-2.894), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.35), new Double(1770.0)},
                {null, "8x19F/W-FE zZ", new Double(-2.253), new Double(-2.569), new Double(1.887), new Double(8.567), new Double(-0.32), new Double(-2.894), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.35), new Double(1770.0)},
                {null, "8x19F/W-SES sZ", new Double(-2.015), new Double(-2.401), new Double(1.588), new Double(8.056), new Double(-0.32), new Double(-2.577), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.42), new Double(1770.0)},
                {null, "8x19F/W-SES zZ", new Double(-1.955), new Double(-2.341), new Double(1.588), new Double(8.056), new Double(-0.32), new Double(-2.577), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.42), new Double(1770.0)},
                {new Boolean(true), "8x36WS-FE sZ", new Double(-1.302), new Double(-1.618), new Double(1.322), new Double(8.07), new Double(-0.32), new Double(-2.649), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.35), new Double(1770.0)},
                {null, "8x36WS-FE zZ", new Double(-1.194), new Double(-1.51), new Double(1.322), new Double(8.07), new Double(-0.32), new Double(-2.649), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.35), new Double(1770.0)},
                {null, "8x36WS-SES sZ", new Double(0.633), new Double(0.247), new Double(0.377), new Double(6.232), new Double(-0.32), new Double(-1.75), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.42), new Double(1770.0)},
                {null, "8x36WS-SES zZ", new Double(0.687), new Double(0.301), new Double(0.377), new Double(6.232), new Double(-0.32), new Double(-1.75), new Double(1.2), new Double(1.9), new Double(1.0), new Double(0.42), new Double(1770.0)}
            },
            new String [] {
                "", "Seiltyp", "b0 / N A", "b0 / N A10", "b1", "b2", "b3", "b4", "b5 / N A", "b5 / N A10", "fn2", "kg/100m/mm²", "N/mm²"
            }
        ) {
            @SuppressWarnings("unchecked")
			Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            @SuppressWarnings("unchecked")
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(parameterTable);

        hinzuButton.setText("Seiltyp hinzuf.");
        hinzuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hinzuButtonActionPerformed(evt);
            }
        });

        entfButton.setText("Seiltyp entf.");
        entfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entfButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Vorgabewerte wiederherstellen");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        saveButton.setText("Datei sichern");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setText("Datei laden");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(hinzuButton)
                                .addGap(6, 6, 6)
                                .addComponent(entfButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hinzuButton)
                    .addComponent(entfButton)
                    .addComponent(resetButton)
                    .addComponent(saveButton)
                    .addComponent(loadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
    	mainFrame.openFileSeil();
        Thread thread = new Thread() {
            @Override
        	public void run() {
        		try {
        			while (!opened) {
        				sleep(50);
        			}
        	        opened = false;
        	        parameterTable.setModel(mainFrame.getParameterTableModel());
        	        setParameterTableLook();
				}
				catch (InterruptedException e) {
					e.printStackTrace();
				}
        	}
        };
        thread.start();
    }//GEN-LAST:event_loadButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    	mainFrame.fileSaveAsSeil();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
    	if (dialogFrame == null || !dialogFrame.isShowing()) {
			dialogFrame = new DialogFrame(this, "M"+SystemConstants.OE_K+"chten Sie die vorgegebenen Seilparameter wiederherstellen?", Constants.DIALOG_RESET, false);
			GUIHelper.showFrame(dialogFrame, this);
    	}
    }//GEN-LAST:event_resetButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    	mainFrame.setEnabled(true);
    	dispose();
    }//GEN-LAST:event_formWindowClosing

    private void entfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entfButtonActionPerformed
    	if (parameterTable.getSelectedRow() != -1) {
	    	if (dialogFrame == null || !dialogFrame.isShowing()) {
				String seiltyp = (String)parameterTable.getValueAt(parameterTable.getSelectedRow(), 1);
				dialogFrame = new DialogFrame(this, "Parameter des Seiltyps '" + seiltyp + "' entfernen?", Constants.DIALOG_REMOVE, false);
				GUIHelper.showFrame(dialogFrame, this);
			}
    	}
    }//GEN-LAST:event_entfButtonActionPerformed

    @SuppressWarnings("unchecked")
	private void hinzuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hinzuButtonActionPerformed
    	if (parameterTable.getSelectedRow() != -1) {
    		DefaultTableModel model = (DefaultTableModel)parameterTable.getModel();
    		Vector nullvector = new Vector();
    		model.addRow(nullvector);
    	}
    	else {
    		DefaultTableModel model = (DefaultTableModel)parameterTable.getModel();
    		Vector nullvector = new Vector();
    		model.addRow(nullvector);
    		//model.
    	}
    }//GEN-LAST:event_hinzuButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    	mainFrame.setEnabled(true);
    	dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    	mainFrame.createErgebnisTable();
    	try {
			mainFrame.saveSeilparameterFile();
		}
		catch (FileSetWritableException e) {
			logger.log(Level.SEVERE, "File "+Constants.SEIL_FILENAME+" can not be set writable! Error in saving!");
			ErrorFrame errorFrame = new ErrorFrame(this, "Datei "+Constants.SEIL_FILENAME+" kann nicht schreibbar gemacht werden! Fehler beim Speichern!"); 
			GUIHelper.showFrame(errorFrame, this);
		}
    	mainFrame.setEnabled(true);
		mainFrame.parameterChanged();
    	dispose();
    }//GEN-LAST:event_okButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton entfButton;
    private javax.swing.JButton hinzuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTable parameterTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

	public void okClicked(Component child) {
		setEnabled(true);
		if (child.getName().equals(Constants.DIALOG_REMOVE)) {
			DefaultTableModel model = (DefaultTableModel)parameterTable.getModel();
			if (parameterTable.getSelectedRow() != -1) model.removeRow(parameterTable.getSelectedRow());
		}
		else if (child.getName().equals(Constants.DIALOG_RESET)) {
			SeilParameterFrame frame = new SeilParameterFrame(mainFrame, null);
			parameterTable.setModel(frame.getParameterTable().getModel());
	        setParameterTableLook();
	        mainFrame.setParameterTableModel(parameterTable.getModel());
		}
	}

	/**
	 * @return the parameterTable
	 */
	public javax.swing.JTable getParameterTable() {
		return parameterTable;
	}

	public void noClicked(Component child) {
		setEnabled(true);
	}

	public void setOpened(boolean opened) {
		this.opened = opened;
	}

	public void somethingChanged() {
		throw new UnsupportedOperationException("Not supported yet.");
	}
    
}
