/*
 * PrintDialog.java
 *
 * Created on 17. Juli 2007, 15:08
 */

package de.tbosch.aufzugseile.gui.utils.printing;

import de.tbosch.commons.gui.printing.TextFieldLimiter;
import de.tbosch.commons.gui.printing.PreviewDialog;
import de.tbosch.commons.gui.printing.Messages;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.Book;
import java.awt.print.PageFormat;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Date;

import de.tbosch.aufzugseile.gui.MainFrame;
import de.tbosch.commons.gui.Reactor;
import java.util.logging.Logger;

/**
 *
 * @author  bobo
 */
public class PrintDialog extends javax.swing.JFrame {
    
    /** The Logger */
    private static final Logger logger = Logger.getLogger(PrintDialog.class.getName());
    
	private Reactor mainFrame;
	private Book book;
	private PrinterJob job;
	private PrintFrameMain printFrame;
	private PrintFrameFeyrer printFrameFeyrer;
	private PageFormat pageFormat;
    
    /** Creates new form PrintDialog */
    public PrintDialog(Reactor mainFrame2, Book book, PrinterJob job) {
    	initComponents();
    	this.pageFormat = book.getPageFormat(0);
    	this.mainFrame = mainFrame2;
    	this.book = book;
    	this.job = job;
		printFrame = (PrintFrameMain)book.getPrintable(0);
		printFrameFeyrer = (PrintFrameFeyrer)book.getPrintable(1);
		printFrame.addWindowListener(new WindowAdapter() {
            @Override
			public void windowClosing(WindowEvent evt) {
				printFrame.dispose();
				printFrameFeyrer.dispose();
				mainFrame.setEnabled(true);
				dispose();
			}
		});
		printFrameFeyrer.addWindowListener(new WindowAdapter() {
            @Override
			public void windowClosing(WindowEvent evt) {
				printFrame.dispose();
				printFrameFeyrer.dispose();
				mainFrame.setEnabled(true);
				dispose();
			}
		});
		getFooterValues();
    	
    	sprachebuttonGroup.add(deutschRadioButton);
    	sprachebuttonGroup.add(englischRadioButton);
    }

	/**
	 * Gets the footer values.
	 */
	private void getFooterValues() {
		String datei = ((MainFrame)mainFrame).getFilename();
		String nutzer = System.getProperty("user.name");
		Date date = new Date();
		SimpleDateFormat df = new SimpleDateFormat( "dd.MM.yyyy - HH:mm:ss" );
		String datum = df.format(date);

		bezeichnungTextField.setDocument(new TextFieldLimiter(28));
		dateiTextField.setText(datei);
		nutzerTextField.setText(nutzer);
		datumTextField.setText(datum);
		
    	printFrame.getDateiLabel().setText(datei);
    	printFrame.getNutzerLabel().setText(nutzer);
    	printFrame.getDatumLabel().setText(datum);
		
    	printFrameFeyrer.getDateiLabel().setText(datei);
    	printFrameFeyrer.getNutzerLabel().setText(nutzer);
    	printFrameFeyrer.getDatumLabel().setText(datum);
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sprachebuttonGroup = new javax.swing.ButtonGroup();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        aufzugRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        parameterRadioButton = new javax.swing.JRadioButton();
        ergebnisseRadioButton = new javax.swing.JRadioButton();
        feyrerRadioButton = new javax.swing.JRadioButton();
        previewButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bezeichnungTextField = new javax.swing.JTextField();
        datumTextField = new javax.swing.JTextField();
        nutzerTextField = new javax.swing.JTextField();
        dateiTextField = new javax.swing.JTextField();
        deutschRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        englischRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Druckvorgang");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("Drucken");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        aufzugRadioButton.setSelected(true);
        aufzugRadioButton.setText("Aufzugskizze");
        aufzugRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        aufzugRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        aufzugRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aufzugRadioButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Druckvorgang");

        jLabel2.setText("Zu drucken:");

        parameterRadioButton.setSelected(true);
        parameterRadioButton.setText("Parameter");
        parameterRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        parameterRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        parameterRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parameterRadioButtonActionPerformed(evt);
            }
        });

        ergebnisseRadioButton.setSelected(true);
        ergebnisseRadioButton.setText("Ergebnisse");
        ergebnisseRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        ergebnisseRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ergebnisseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ergebnisseRadioButtonActionPerformed(evt);
            }
        });

        feyrerRadioButton.setSelected(true);
        feyrerRadioButton.setText("Seilparameter nach Feyrer (2. Seite)");
        feyrerRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        feyrerRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        feyrerRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feyrerRadioButtonActionPerformed(evt);
            }
        });

        previewButton.setText("Vorschau");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Anlagenbezeichnung:");

        jLabel4.setText("Datum:");

        jLabel5.setText("Ersteller:");

        jLabel6.setText("Dateiname:");

        bezeichnungTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bezeichnungTextFieldKeyReleased(evt);
            }
        });

        datumTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datumTextFieldKeyReleased(evt);
            }
        });

        nutzerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nutzerTextFieldKeyReleased(evt);
            }
        });

        dateiTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateiTextFieldKeyReleased(evt);
            }
        });

        deutschRadioButton.setSelected(true);
        deutschRadioButton.setText("deutsch");
        deutschRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deutschRadioButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Sprachversion");

        englischRadioButton.setText("englisch");
        englischRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englischRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aufzugRadioButton)
                                    .addComponent(jLabel2)
                                    .addComponent(parameterRadioButton)
                                    .addComponent(ergebnisseRadioButton)
                                    .addComponent(feyrerRadioButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(previewButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bezeichnungTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(datumTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateiTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addComponent(nutzerTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deutschRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(englischRadioButton))
                            .addComponent(jLabel7))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bezeichnungTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nutzerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aufzugRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parameterRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ergebnisseRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(feyrerRadioButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deutschRadioButton)
                    .addComponent(englischRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton)
                    .addComponent(previewButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateiTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateiTextFieldKeyReleased
    	printFrame.getDateiLabel().setText(dateiTextField.getText());
    	printFrameFeyrer.getDateiLabel().setText(dateiTextField.getText());
    }//GEN-LAST:event_dateiTextFieldKeyReleased

    private void nutzerTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nutzerTextFieldKeyReleased
    	printFrame.getNutzerLabel().setText(nutzerTextField.getText());
    	printFrameFeyrer.getNutzerLabel().setText(nutzerTextField.getText());
    }//GEN-LAST:event_nutzerTextFieldKeyReleased

    private void datumTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datumTextFieldKeyReleased
    	printFrame.getDatumLabel().setText(datumTextField.getText());
    	printFrameFeyrer.getDatumLabel().setText(datumTextField.getText());
    }//GEN-LAST:event_datumTextFieldKeyReleased

    private void bezeichnungTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bezeichnungTextFieldKeyReleased
    	printFrame.getBezeichnungLabel().setText(bezeichnungTextField.getText());
    	printFrameFeyrer.getBezeichnungLabel().setText(bezeichnungTextField.getText());
    }//GEN-LAST:event_bezeichnungTextFieldKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    	cancelButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void feyrerRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feyrerRadioButtonActionPerformed
    	if (feyrerRadioButton.isSelected()) {
    		logger.info("Add Feyrer parameters panel to print frame");
    		Book oldBook = book;
    		book = new Book();
    		if (aufzugRadioButton.isSelected() || parameterRadioButton.isSelected() || ergebnisseRadioButton.isSelected()) {
    			book.append(oldBook.getPrintable(0), pageFormat);
    		}
    		book.append(printFrameFeyrer, pageFormat);
    	}
    	else {
    		logger.info("Remove Feyrer parameters from print frame");
    		Book oldBook = book;
    		book = new Book();
    		if (ergebnisseRadioButton.isSelected() || parameterRadioButton.isSelected() || aufzugRadioButton.isSelected()) {
    			book.append(oldBook.getPrintable(0), pageFormat);
    		}
    	}
    }//GEN-LAST:event_feyrerRadioButtonActionPerformed

    private void ergebnisseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ergebnisseRadioButtonActionPerformed
    	if (ergebnisseRadioButton.isSelected()) {
    		if (!aufzugRadioButton.isSelected() && !parameterRadioButton.isSelected()) {
    			logger.info("Add new first page with solution panel to print frame");
    			Book oldBook = book;
    			book = new Book();
    			book.append(printFrame, pageFormat);
    			if (feyrerRadioButton.isSelected()) {
    				book.append(oldBook.getPrintable(0), pageFormat);
    			}
    		}
    		logger.info("Add solution panel to print frame");
    		if (printFrame.getMainSplitPane().getRightComponent() == null) {
    			printFrame.getMainSplitPane().setRightComponent(printFrame.getUSplitPane());
    			printFrame.getMainSplitPane().setDividerLocation(450);
    			printFrame.getUSplitPane().setDividerLocation(110);
    		}
    		printFrame.getUSplitPane().setRightComponent(printFrame.getUuPanel());
    		printFrame.getUSplitPane().setDividerLocation(110);	
    	}
    	else {
    		if (!parameterRadioButton.isSelected() && !aufzugRadioButton.isSelected()) {
    			logger.info("Remove complete first page print frame");
    			Book oldBook = book;
        		book = new Book();
        		if (feyrerRadioButton.isSelected()) {
        			book.append(oldBook.getPrintable(1), pageFormat);
        		}
    		}
    		else {	
    			logger.info("Remove solution panel from print frame");
    			printFrame.getUSplitPane().setRightComponent(null);
        		if (printFrame.getUSplitPane().getLeftComponent() == null) {
        			printFrame.getMainSplitPane().setRightComponent(null);
        		}
    		}
    	}
    }//GEN-LAST:event_ergebnisseRadioButtonActionPerformed

    private void parameterRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parameterRadioButtonActionPerformed
    	if (parameterRadioButton.isSelected()) {
    		if (!aufzugRadioButton.isSelected() && !ergebnisseRadioButton.isSelected()) {
    			logger.info("Add new first page with parameter panel to print frame");
    			Book oldBook = book;
    			book = new Book();
    			book.append(printFrame, pageFormat);
    			if (feyrerRadioButton.isSelected()) {
    				book.append(oldBook.getPrintable(0), pageFormat);
    			}
    		}
    		logger.info("Add parameter panel to print frame");
    		if (printFrame.getMainSplitPane().getRightComponent() == null) {
    			printFrame.getMainSplitPane().setRightComponent(printFrame.getUSplitPane());
    			printFrame.getMainSplitPane().setDividerLocation(450);
    			printFrame.getUSplitPane().setDividerLocation(110);
    		}
    		if (printFrame.getMainSplitPane().getLeftComponent() == null) {
    			printFrame.getMainSplitPane().setLeftComponent(printFrame.getOSplitPane());
    			printFrame.getMainSplitPane().setDividerLocation(450);
    			printFrame.getUSplitPane().setDividerLocation(110);
    		}
    		printFrame.getOSplitPane().setRightComponent(printFrame.getOrPanel());
    		printFrame.getOSplitPane().setDividerLocation(300);
    		printFrame.getUSplitPane().setLeftComponent(printFrame.getUoPanel());
    		printFrame.getUSplitPane().setDividerLocation(110);
    	}
    	else {
    		if (!ergebnisseRadioButton.isSelected() && !aufzugRadioButton.isSelected()) {
    			logger.info("Remove complete first page print frame");
    			Book oldBook = book;
        		book = new Book();
        		if (feyrerRadioButton.isSelected()) {
        			book.append(oldBook.getPrintable(1), pageFormat);
        		}
    		}
    		else {
    			logger.info("Remove parameter panel from print frame");
    			printFrame.getOSplitPane().setRightComponent(null);
    			printFrame.getUSplitPane().setLeftComponent(null);
    			if (printFrame.getUSplitPane().getRightComponent() == null) {
    				printFrame.getMainSplitPane().setRightComponent(null);
    			}
    			if (printFrame.getOSplitPane().getLeftComponent() == null) {
    				printFrame.getMainSplitPane().setLeftComponent(null);
    			}
    		}
    	}
    }//GEN-LAST:event_parameterRadioButtonActionPerformed

    private void aufzugRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aufzugRadioButtonActionPerformed
    	if (aufzugRadioButton.isSelected()) {
    		if (!parameterRadioButton.isSelected() && !ergebnisseRadioButton.isSelected()) {
    			logger.info("Add new first page with aufzug panel to print frame");
    			Book oldBook = book;
    			book = new Book();
    			book.append(printFrame, pageFormat);
    			if (feyrerRadioButton.isSelected()) {
    				book.append(oldBook.getPrintable(0), pageFormat);
    			}
    		}
    		logger.info("Add elevator panel to print frame");
    		if (printFrame.getMainSplitPane().getLeftComponent() == null) {
    			printFrame.getMainSplitPane().setLeftComponent(printFrame.getOSplitPane());
    			printFrame.getMainSplitPane().setDividerLocation(450);
    			printFrame.getUSplitPane().setDividerLocation(110);
    		}
    		printFrame.getOSplitPane().setLeftComponent(printFrame.getOlPanel());
    		printFrame.getOSplitPane().setDividerLocation(300);
    	}
    	else {
    		if (!ergebnisseRadioButton.isSelected() && !parameterRadioButton.isSelected()) {
    			logger.info("Remove complete first page print frame");
    			Book oldBook = book;
        		book = new Book();
        		if (feyrerRadioButton.isSelected()) {
        			book.append(oldBook.getPrintable(1), pageFormat);
        		}
    		}
    		else {
    			logger.info("Remove elevator panel from print frame");
    			printFrame.getOSplitPane().setLeftComponent(null);
    			if (printFrame.getOSplitPane().getRightComponent() == null) {
    				printFrame.getMainSplitPane().setLeftComponent(null);
    			}
    		}
    	}
    }//GEN-LAST:event_aufzugRadioButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
		if (aufzugRadioButton.isSelected() || parameterRadioButton.isSelected()
				|| ergebnisseRadioButton.isSelected() || feyrerRadioButton.isSelected()) {
			PreviewDialog dialog = new PreviewDialog("Vorschau", this, book);
			dialog.setVisible(true);
		}
    }//GEN-LAST:event_previewButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		printFrame.dispose();
		printFrameFeyrer.dispose();
    	mainFrame.setEnabled(true);
    	dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deutschRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deutschRadioButtonActionPerformed
    	Messages.setLanguage("german");
    	resetFrames();
    }//GEN-LAST:event_deutschRadioButtonActionPerformed

    private void englischRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englischRadioButtonActionPerformed
    	Messages.setLanguage("english");
    	resetFrames();
    }//GEN-LAST:event_englischRadioButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
		mainFrame.okClicked(this);
    	dispose();
    }                                        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton aufzugRadioButton;
    private javax.swing.JTextField bezeichnungTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dateiTextField;
    private javax.swing.JTextField datumTextField;
    private javax.swing.JRadioButton deutschRadioButton;
    private javax.swing.JRadioButton englischRadioButton;
    private javax.swing.JRadioButton ergebnisseRadioButton;
    private javax.swing.JRadioButton feyrerRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nutzerTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JRadioButton parameterRadioButton;
    private javax.swing.JButton previewButton;
    private javax.swing.ButtonGroup sprachebuttonGroup;
    // End of variables declaration//GEN-END:variables

	public Book getBook() {
		return book;
	}

	public PrinterJob getJob() {
		return job;
	}

	public PrintFrameMain getPrintFrame() {
		return printFrame;
	}

	public PrintFrameFeyrer getPrintFrameFeyrer() {
		return printFrameFeyrer;
	}
  
	/**
	 * Reset the frames for changing language strings.
	 * Reset all check boxes
	 */
	private void resetFrames() {		
		printFrame.dispose();
		printFrameFeyrer.dispose();
    	book = new Book();
    	printFrame = new PrintFrameMain();
		printFrame.insertAufzugschacht(((MainFrame)mainFrame).getAufzugschacht(), (MainFrame)mainFrame);
		printFrame.setVisible(true);
		printFrame.setExtendedState(ICONIFIED);
		book.append(printFrame, pageFormat);
		printFrameFeyrer = new PrintFrameFeyrer();
		printFrameFeyrer.insertUsedFeyrerParameters((MainFrame)mainFrame);
		if (((MainFrame)mainFrame).getBerechnung().getCalcRolls().size() > 0) printFrameFeyrer.createEinzelErgebnisTables((MainFrame)mainFrame);
		printFrameFeyrer.setVisible(true);
		printFrameFeyrer.setExtendedState(ICONIFIED);
		book.append(printFrameFeyrer, pageFormat);
		feyrerRadioButton.setSelected(true);
		parameterRadioButton.setSelected(true);
		ergebnisseRadioButton.setSelected(true);
		aufzugRadioButton.setSelected(true);
		getFooterValues();
	}
}
