package de.tbosch.aufzugseile.gui;

import javax.swing.ImageIcon;

import de.tbosch.aufzugseile.utils.Constants;
import de.tbosch.aufzugseile.utils.Helper;

/**
 * The form to set the elevator dimensions in width and height
 *
 * @author Thomas Bosch (tbosch@gmx.de)
 */
public class SchachtFrame extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 4043716791878295468L;

	/** The main frame. */
    private MainFrame mainFrame;
    
    /** Indicates if the frame was opened at start. */
    private boolean start;
    
    /**
     * Creates new form SchachtFrame.
     * 
     * @param mainFrame the main frame
     */
    public SchachtFrame(MainFrame mainFrame) {
    	initComponents();
    	this.mainFrame = mainFrame;
    	if (mainFrame.getAufzugschacht() != null) {
    		if (mainFrame.getAufzugschacht().getHoehe() != 0) {
    			hoeheTextField.setText(Integer.toString(mainFrame.getAufzugschacht().getHoehe()));
    		}
    		else {
    			start = true;
    		}
    		if (mainFrame.getAufzugschacht().getBreite() != 0) {
    			breiteTextField.setText(Integer.toString(mainFrame.getAufzugschacht().getBreite()));
    		}
    		else {
    			start = true;
    		}
    	}
		else {
			start = true;
		}
    	if (start) {
    		cancelButton.setEnabled(false);
    	}
    	
		ImageIcon imageIcon = new ImageIcon(Helper.getFileURL(Constants.PROGRAM_ICON));
		setIconImage(imageIcon.getImage());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        titelLabel = new javax.swing.JLabel();
        breiteLabel = new javax.swing.JLabel();
        hoeheLabel = new javax.swing.JLabel();
        breiteTextField = new javax.swing.JTextField();
        breiteEinheitLabel = new javax.swing.JLabel();
        hoeheTextField = new javax.swing.JTextField();
        hoeheEinheitLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Schachtausma\u00dfe");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titelLabel.setText("Ausma\u00dfe des Aufzugschachts:");

        breiteLabel.setText("Schachtbreite:");

        hoeheLabel.setText("F\u00f6rderh\u00f6he:");

        breiteEinheitLabel.setText("cm (> 0)");

        hoeheEinheitLabel.setText("m (>= 0)");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(breiteLabel)
                            .addComponent(hoeheLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hoeheTextField)
                            .addComponent(breiteTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breiteEinheitLabel)
                            .addComponent(hoeheEinheitLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addComponent(cancelButton))))
                    .addComponent(titelLabel)
                    .addComponent(errorLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titelLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breiteLabel)
                    .addComponent(breiteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breiteEinheitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hoeheLabel)
                    .addComponent(hoeheTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoeheEinheitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(okButton)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    	if (!start) {
    		mainFrame.setEnabled(true);
    		dispose();
    	}
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    	cancelButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
    	isOkay();
    }//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel breiteEinheitLabel;
    private javax.swing.JLabel breiteLabel;
    private javax.swing.JTextField breiteTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel hoeheEinheitLabel;
    private javax.swing.JLabel hoeheLabel;
    private javax.swing.JTextField hoeheTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel titelLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Checks if the entries are okay.
     */
    private void isOkay() {
    	int breite, hoehe;
    	breite = Helper.getIntFromTextField(breiteTextField);
    	hoehe = Helper.getIntFromTextField(hoeheTextField);
    	if (breite > 0 && hoehe >= 0) {
    		mainFrame.schachtReady(breite, hoehe);
    		dispose();
    	}
    	else {
    		errorLabel.setText("Breite oder H"+Constants.OE_K+"he nicht korrekt!");
    	}
    }
}
