/*
 * LoadFileDialog.java
 *
 * Created on 19. September 2007, 21:03
 */

package de.tbosch.aufzugseile.gui;

/**
 * 
 * @author Thomas Bosch (tbosch@gmx.de)
 */
public class LoadFileDialog extends javax.swing.JDialog {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4678637604123541788L;

	/** The main frame. */
	private MainFrame mainFrame;

	/** Creates new form LoadFileDialog */
	public LoadFileDialog(MainFrame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.mainFrame = parent;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {
		jLabel1 = new javax.swing.JLabel();
		neinButton = new javax.swing.JButton();
		jaButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jLabel1.setText("M\u00f6chten Sie einen existierenden Aufzug laden?");

		neinButton.setText("Nein");
		neinButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				neinButtonActionPerformed(evt);
			}
		});

		jaButton.setText("Ja");
		jaButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jaButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addContainerGap(94, Short.MAX_VALUE)).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(274, Short.MAX_VALUE).addComponent(jaButton).addPreferredGap(
						javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(neinButton).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39,
						Short.MAX_VALUE).addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(neinButton).addComponent(jaButton))
						.addContainerGap()));
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		neinButtonActionPerformed(null);
	}// GEN-LAST:event_formWindowClosing

	private void jaButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jaButtonActionPerformed
		mainFrame.setLoadFile(true);
		mainFrame.setEnabled(true);
		dispose();
	}// GEN-LAST:event_jaButtonActionPerformed

	private void neinButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_neinButtonActionPerformed
		mainFrame.setLoadFile(false);
		mainFrame.setEnabled(true);
		dispose();
	}// GEN-LAST:event_neinButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JButton jaButton;
	private javax.swing.JButton neinButton;
	// End of variables declaration//GEN-END:variables

}
