package de.tbosch.aufzugseile.gui.utils.printing;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.print.Book;
import java.awt.print.PageFormat;
import java.awt.print.PrinterJob;
import java.text.SimpleDateFormat;
import java.util.Date;

import de.tbosch.aufzugseile.gui.MainFrame;
import de.tbosch.aufzugseile.gui.TreibfaehigkeitFrame;
import de.tbosch.aufzugseile.gui.utils.ReactingFrame;


/**
 *
 * @author  bobo
 */
public class PrintDialogTreib extends javax.swing.JFrame {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 7399120400537366859L;
	private ReactingFrame treibFrame;
	private Book book;
	private PrinterJob job;
	private PrintFrameTreib printFrameTreib;
	private MainFrame mainFrame;
    
    /** Creates new form PrintDialog */
    public PrintDialogTreib(ReactingFrame treibFrame2, Book book, PrinterJob job, MainFrame mainFrame) {
    	initComponents();
    	this.treibFrame = treibFrame2;
    	this.mainFrame = mainFrame;
    	this.book = book;
    	this.job = job;
		printFrameTreib = (PrintFrameTreib)book.getPrintable(0);
		printFrameTreib.addWindowListener(new WindowAdapter() {
			public void windowClosing(WindowEvent evt) {
				printFrameTreib.dispose();
				treibFrame.setEnabled(true);
				dispose();
			}
		});
		getFooterValues();
    	
    	sprachbuttonGroup.add(deutschRadioButton);
    	sprachbuttonGroup.add(englischRadioButton);
    	
    	setAlwaysOnTop(true);
    }

	/**
	 * Gets the footer values.
	 */
	private void getFooterValues() {
		String datei = mainFrame.getFilename();
		String nutzer = System.getProperty("user.name");
		Date date = new Date();
		SimpleDateFormat df = new SimpleDateFormat( "dd.MM.yyyy - HH:mm:ss" );
		String datum = df.format(date);

		bezeichnungTextField.setDocument(new TextFieldLimiter(28));
		dateiTextField.setText(datei);
		nutzerTextField.setText(nutzer);
		datumTextField.setText(datum);
		
    	printFrameTreib.getDateiLabel().setText(datei);
    	printFrameTreib.getNutzerLabel().setText(nutzer);
    	printFrameTreib.getDatumLabel().setText(datum);
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sprachbuttonGroup = new javax.swing.ButtonGroup();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        previewButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bezeichnungTextField = new javax.swing.JTextField();
        datumTextField = new javax.swing.JTextField();
        nutzerTextField = new javax.swing.JTextField();
        dateiTextField = new javax.swing.JTextField();
        deutschRadioButton = new javax.swing.JRadioButton();
        englischRadioButton = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Druckvorgang");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("Drucken");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Druckvorgang");

        previewButton.setText("Vorschau");
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Anlagenbezeichnung:");

        jLabel4.setText("Datum:");

        jLabel5.setText("Ersteller:");

        jLabel6.setText("Dateiname:");

        bezeichnungTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bezeichnungTextFieldKeyReleased(evt);
            }
        });

        datumTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                datumTextFieldKeyReleased(evt);
            }
        });

        nutzerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nutzerTextFieldKeyReleased(evt);
            }
        });

        dateiTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateiTextFieldKeyReleased(evt);
            }
        });

        deutschRadioButton.setSelected(true);
        deutschRadioButton.setText("deutsch");
        deutschRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deutschRadioButtonActionPerformed(evt);
            }
        });

        englischRadioButton.setText("englisch");
        englischRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englischRadioButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Sprachversion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(previewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bezeichnungTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(datumTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(dateiTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                .addComponent(nutzerTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(deutschRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(englischRadioButton))
                            .addComponent(jLabel7))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bezeichnungTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nutzerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dateiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deutschRadioButton)
                    .addComponent(englischRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(previewButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dateiTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateiTextFieldKeyReleased
    	printFrameTreib.getDateiLabel().setText(dateiTextField.getText());
    }//GEN-LAST:event_dateiTextFieldKeyReleased

    private void nutzerTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nutzerTextFieldKeyReleased
    	printFrameTreib.getNutzerLabel().setText(nutzerTextField.getText());
    }//GEN-LAST:event_nutzerTextFieldKeyReleased

    private void datumTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datumTextFieldKeyReleased
    	printFrameTreib.getDatumLabel().setText(datumTextField.getText());
    }//GEN-LAST:event_datumTextFieldKeyReleased

    private void bezeichnungTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bezeichnungTextFieldKeyReleased
    	printFrameTreib.getBezeichnungLabel().setText(bezeichnungTextField.getText());
    }//GEN-LAST:event_bezeichnungTextFieldKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    	cancelButtonActionPerformed(null);
    }//GEN-LAST:event_formWindowClosing

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
		PreviewDialog dialog = new PreviewDialog("Vorschau", this, book);
		dialog.setVisible(true);
    }//GEN-LAST:event_previewButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		printFrameTreib.dispose();
    	treibFrame.setEnabled(true);
    	dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void deutschRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deutschRadioButtonActionPerformed
    	Messages.setLanguage("german");
    	resetFrame();
    }//GEN-LAST:event_deutschRadioButtonActionPerformed

    private void englischRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englischRadioButtonActionPerformed
    	Messages.setLanguage("english");
    	resetFrame();
    }//GEN-LAST:event_englischRadioButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	treibFrame.okClicked(this);
    	dispose();
    }                                        
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bezeichnungTextField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dateiTextField;
    private javax.swing.JTextField datumTextField;
    private javax.swing.JRadioButton deutschRadioButton;
    private javax.swing.JRadioButton englischRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nutzerTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JButton previewButton;
    private javax.swing.ButtonGroup sprachbuttonGroup;
    // End of variables declaration//GEN-END:variables

	public Book getBook() {
		return book;
	}

	public PrinterJob getJob() {
		return job;
	}

	public PrintFrameTreib getPrintFrameTreib() {
		return printFrameTreib;
	}
  
	/**
	 * Reset the frame for changing language strings.
	 */
	private void resetFrame() {		
		printFrameTreib.dispose();
    	PageFormat pageFormat = book.getPageFormat(0);
    	book = new Book();
    	printFrameTreib = new PrintFrameTreib();
		printFrameTreib.insertUsedTreibParameters((TreibfaehigkeitFrame)treibFrame);
		printFrameTreib.setVisible(true);
		printFrameTreib.setExtendedState(ICONIFIED);
		book.append(printFrameTreib, pageFormat);
		getFooterValues();
	}
}
