package de.tbosch.aufzugseile.gui.utils.printing;

import java.awt.Graphics;
import java.awt.print.PageFormat;
import java.awt.print.Printable;

import javax.swing.ImageIcon;
import javax.swing.RepaintManager;

import de.tbosch.aufzugseile.gui.TreibfaehigkeitFrame;
import de.tbosch.aufzugseile.utils.Helper;

/**
 *
 * @author Thomas Bosch (tbosch@gmx.de)
 */
public class PrintFrameTreib extends javax.swing.JFrame implements Printable {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -2423434685213588748L;
	
	/** Creates new form PrintFrameTreib */
    public PrintFrameTreib() {
    	initComponents();
    	setResizable(false);
		setTitle("Preview 3 - DO NOT CLOSE"); //$NON-NLS-1$
		jLabel1.setIcon(new ImageIcon(Helper.getFileURL("images/drako_200.jpg"))); //$NON-NLS-1$
    }
    
    /* (non-Javadoc)
     * @see java.awt.print.Printable#print(java.awt.Graphics, java.awt.print.PageFormat, int)
     */
    public int print(Graphics g, PageFormat pageFormat, int pageIndex) {
		int x = (int)pageFormat.getImageableX() + 1;
		int y = (int)pageFormat.getImageableY() + 1;
		g.translate(x, y);
		RepaintManager currentManager = RepaintManager.currentManager(this);
		currentManager.setDoubleBufferingEnabled(false);
		paint(g);
		currentManager.setDoubleBufferingEnabled(true);
		return (PAGE_EXISTS);
	}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    @SuppressWarnings("serial") //$NON-NLS-1$
	private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        uPanel = new javax.swing.JPanel();
        tableScrollPane = new javax.swing.JScrollPane();
        treibTable = new javax.swing.JTable();
        oPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bezeichnungLabel = new javax.swing.JLabel();
        uuuPanel = new javax.swing.JPanel();
        nutzerLabel = new javax.swing.JLabel();
        dateiLabel = new javax.swing.JLabel();
        datumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        uPanel.setBackground(new java.awt.Color(255, 255, 255));
        uPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(Messages.getString("PrintFrameTreib.3"))); //$NON-NLS-1$
        uPanel.setLayout(new java.awt.GridLayout(1, 0));

        tableScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        treibTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                Messages.getString("PrintFrameTreib.4"), Messages.getString("PrintFrameTreib.5") //$NON-NLS-1$ //$NON-NLS-2$
            }
        ) {
            @SuppressWarnings("unchecked") //$NON-NLS-1$
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            @SuppressWarnings("unchecked") //$NON-NLS-1$
			public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableScrollPane.setViewportView(treibTable);

        uPanel.add(tableScrollPane);

        oPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(Messages.getString("PrintFrameTreib.8"))); //$NON-NLS-1$

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bezeichnungLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bezeichnungLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 12, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout oPanelLayout = new javax.swing.GroupLayout(oPanel);
        oPanel.setLayout(oPanelLayout);
        oPanelLayout.setHorizontalGroup(
            oPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oPanelLayout.createSequentialGroup()
                .addContainerGap(540, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        oPanelLayout.setVerticalGroup(
            oPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        uuuPanel.setBackground(new java.awt.Color(255, 255, 255));
        uuuPanel.setLayout(new java.awt.GridLayout(1, 0));

        nutzerLabel.setText(Messages.getString("PrintFrameTreib.9")); //$NON-NLS-1$
        uuuPanel.add(nutzerLabel);

        dateiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateiLabel.setText(Messages.getString("PrintFrameTreib.10")); //$NON-NLS-1$
        uuuPanel.add(dateiLabel);

        datumLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        datumLabel.setText(Messages.getString("PrintFrameTreib.11")); //$NON-NLS-1$
        uuuPanel.add(datumLabel);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(oPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(uuuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addComponent(uPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(oPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uuuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bezeichnungLabel;
    private javax.swing.JLabel dateiLabel;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nutzerLabel;
    private javax.swing.JPanel oPanel;
    private javax.swing.JScrollPane tableScrollPane;
    private javax.swing.JTable treibTable;
    private javax.swing.JPanel uPanel;
    private javax.swing.JPanel uuuPanel;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Insert used feyrer parameters.
     * 
     * @param treibFrame the treib frame
     */
    public void insertUsedTreibParameters(TreibfaehigkeitFrame treibFrame) {
		treibTable.getTableHeader().setFont(new java.awt.Font("Dialog", 0, 10)); //$NON-NLS-1$
		treibTable.setFont(new java.awt.Font("Dialog", 0, 10)); //$NON-NLS-1$
		treibTable.setRowHeight(12);
		treibTable.getColumnModel().getColumn(0).setPreferredWidth(200);
		treibTable.getColumnModel().getColumn(0).setMaxWidth(200);
		treibTable.getColumnModel().getColumn(0).setMinWidth(200);
    	int i = 0;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.14"), i, 0); //$NON-NLS-1$
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.42"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getSeilmasseFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.43"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getSeilanzahlTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.15"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getKabinekraftFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.16"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getGewichtkraftFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.17"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getHkkraftFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.18"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getTskraftFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.19"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getHubhoeheFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.20"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getUmschlWinkelFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.21"), i, 0); //$NON-NLS-1$
    	if (treibFrame.getKleingueterRadioButton().isSelected()) treibTable.setValueAt(Messages.getString("PrintFrameTreib.22"), i, 1); //$NON-NLS-1$
    	if (treibFrame.getFassadeRadioButton().isSelected()) treibTable.setValueAt(Messages.getString("PrintFrameTreib.23"), i, 1); //$NON-NLS-1$
    	if (treibFrame.getSonstigerRadioButton().isSelected()) treibTable.setValueAt(Messages.getString("PrintFrameTreib.24"), i, 1); //$NON-NLS-1$
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.25"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getPhiFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.26"), i, 0); //$NON-NLS-1$
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.27"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getT2t1FormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.28"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getS2s1FormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.29"), i, 0); //$NON-NLS-1$
    	treibTable.setValueAt(treibFrame.getPressungFormattedTextField().getText(), i, 1);
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.30"), i, 0); //$NON-NLS-1$
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.31"), i, 0); //$NON-NLS-1$
    	if (treibFrame.isTSphiIO()) treibTable.setValueAt(Messages.getString("PrintFrameTreib.32"), i, 1); //$NON-NLS-1$
    	else treibTable.setValueAt(Messages.getString("PrintFrameTreib.33"), i, 1); //$NON-NLS-1$
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.34"), i, 0); //$NON-NLS-1$
    	if (treibFrame.isPressIO()) treibTable.setValueAt(Messages.getString("PrintFrameTreib.35"), i, 1); //$NON-NLS-1$
    	else treibTable.setValueAt(Messages.getString("PrintFrameTreib.36"), i, 1); //$NON-NLS-1$
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.37"), i, 0); //$NON-NLS-1$
    	if (treibFrame.isSonstIO()) treibTable.setValueAt(Messages.getString("PrintFrameTreib.38"), i, 1); //$NON-NLS-1$
    	else treibTable.setValueAt(Messages.getString("PrintFrameTreib.39"), i, 1); //$NON-NLS-1$
    	i++;
    	treibTable.setValueAt(Messages.getString("PrintFrameTreib.40"), i, 0); //$NON-NLS-1$
    	if (!treibFrame.isCalced()) treibTable.setValueAt(Messages.getString("PrintFrameTreib.41"), i, 1); //$NON-NLS-1$
    	else treibTable.setValueAt(treibFrame.getBemerkungenTextArea().getText(), i, 1);
    }

	public javax.swing.JLabel getBezeichnungLabel() {
		return bezeichnungLabel;
	}

	public javax.swing.JLabel getDateiLabel() {
		return dateiLabel;
	}

	public javax.swing.JLabel getDatumLabel() {
		return datumLabel;
	}

	public javax.swing.JLabel getNutzerLabel() {
		return nutzerLabel;
	}
}	
